### PR TITLE
Changes to Ships and Astronauts, Added Pilot and SpaceCapsule

### PR DESCRIPTION
**Pull request by AmiChaib**
Hello, I hope this is okay.

### CODE REVIEW

**Comment by AmiChaib** [comment]
Idk in the Modules it just feels like far too much repetition. How do we best fix that?
--> Dock and Core or Gym and Crew modules have exact same methods, while Research and Maintenance also have the same ones but with different types of Astronauts.

**Comment by TomiEckert** [comment]
I just rechecked the `transfer` method. Jesus... If there's no more space in the capsule, the rest of the astronauts explode... If no one stays nothing explodes.

**Comment by AmiChaib** [comment]
Jo I never said the CrewShip explodes.. Also they should make sure there's enough evacuation capsules for everyone, but if it's full it's full

**Comment by TomiEckert** [comment]
My bad. You can still make it explode 🤷

**Pull request merged**
